### ISSUE TITLE
Rework the website after removing js files

### ISSUE THREAD

**Issue by vilie** [rosedu/uc.rosedu.org#24]
The best solution I found so far was spiting the website into multiple static pages with each of them containing the data as like before the js removal. I am trying to find a convenient way to make this process automatic (as there are a lot of webpages).

The second choice would be a clean-room design of the past scripts. I have no web knowledge and I can't estimate the effort for that.

I started working on the first solution, if anyone has a better suggestion, please reply.

**Comment by tudalex** [comment]
I'll take a look at how easy it is to replace everything with angularjs and replace the datasources with json files.

**Comment by vilie** [comment]
OK. I started looking into restoring the site functionality (design, navigation) as with was heavily based on main.js.

**Comment by vilie** [comment]
I restored site navigation functionality. Logos and other images show fine now. Stats per track do not work yet but they are no longer a priority.

I will see how can we fix them in the following weeks. :-)

**Comment by vilie** [comment]
No longer in scope.
